### ISSUE TITLE
enablePlugins(var) need import something

### ISSUE THREAD

**Issue by mycoco2014** [playframework/twirl#101]
we have more project .we need  `import play.twirl.sbt._` in porject build file. 

`someproject.enablePlugins(SbtTwirl)` or 
`someproject.enablePlugins(play.twirl.sbt.SbtTwirl )`

**Comment by schmitch** [comment]
I'm not really understanding what you meant. Actually for help you can take a look at the mailing list here: https://groups.google.com/forum/#!forum/play-framework
if you still find an issue try to reopen it if needed.
