### ISSUE TITLE
String interpolation in templates

### ISSUE THREAD

**Issue by makkarpov** [playframework/twirl#103]
Currently Twirl does not support string interpolation in templates, I think mostly because simple string interpolation can be done with Twirl itself, like `Hello, @name!`. But more complex string interpolators cannot be substituted with Twirl. The sample of such interpolator is a translating interpolator at my project, [Scalingua](https://github.com/makkarpov/scalingua). Currently we have to write

``` scala
  @(t"Hello, world!")
```

Could Twirl compiler support shorter and cleaner version of it, something like

``` scala
  @t"Hello, world!"
```

This is a pretty minor issue, of course, but these parentheses looks ugly, and adding string interpolation syntax should not break any existing code.

**Comment by julienrf** [comment]
Isn’t it possible if you use braces or parens?

~~~ scala
@{ t"Hello, world" }

@( t"Hello, world" )
~~~

**Comment by makkarpov** [comment]
I mentioned it that it's possible using parens, but I see no obstacles to add it as a syntax feature

**Comment by gmethvin** [comment]
I think that introduces some ambiguity, though, or at least a backwards-incompatible syntax change. Now `@t"foo"` is an interpolated string, whereas before it was a variable followed by a literal quoted string.

**Comment by makkarpov** [comment]
Hm. I haven't checked it yet, but seems like before a string like `@t"foo"` was an invalid syntax, so it should not be encountered in any existing templates.

**Comment by schmitch** [comment]
actually `@t"foo"` isn't invalid syntax it will be rendered as 'content of variable t'"foo". Actually it would make it impossible to have a variable `t` combined with a string that contains `"` at the begin and end without a whitespace in between

**Comment by gmethvin** [comment]
closing since there's no clear way I see to introduce this new syntax without breaking changes.
