### ISSUE TITLE
sbt 1.0

### ISSUE THREAD

**Issue by antonkulaga** [playframework/twirl#104]
Please, add sbt 1.0 support ( http://www.scala-sbt.org/1.0/docs/Community-Plugins.html )

### Dependencies

- [x] ~https://github.com/scala-js/scala-js/pull/3075~
- [x] https://github.com/playframework/interplay/issues/27

**Comment by schmitch** [comment]
Can be closed due to https://github.com/playframework/twirl/pull/138
