### ISSUE TITLE
Support Scala as target language

### ISSUE THREAD

**Issue by jeffmay** [playframework/twirl#123]
I would like to create an `Example.scala.scala` template for generating Scala code with Twirl. Right now, anything that isn't a supported format is excluded from the plugin. Why is this? Couldn't this project theoretically support any filetype?

My current workaround is to use `.txt` and then dump it to a `.scala` file.

**Comment by jpz** [comment]
Would this solve your problem?  I believe it's extensible.

https://www.playframework.com/documentation/2.5.x/ScalaCustomTemplateFormat

**Comment by jeffmay** [comment]
Yup. I was able to get this working pretty easily by just creating a `ScalaFormat` object and adding it to the `TwirlKeys.templateFormats`. Thanks!
