### ISSUE TITLE
how to override variable in children page

### ISSUE THREAD

**Issue by caoguangyao** [playframework/twirl#134]
for example ,I have a base.scala.html

> @(title:String)(menu:Html)(content:Html)
@sub_menu1={class="active"}
@sub_menu2={}
@menu={
<a @sub_menu1 href="@routes.Controller.link1">link1</a>
<a @sub_menu2 href="@routes.Controller.link2">link2</a>
}
@main(title)(menu){content}

my second page is sub_page.scala.html

> @sub_menu1={}
sub_menu2={class="active"}
@base(title){some content}

then  sub_men1 and sub_menu2 in sub_page.scala.html seem as normal variable, not release to base.scala.html.I want them to inherase the base page and rewrite value to show a dynamic menu
how to do with this issue

**Comment by marcospereira** [comment]
Hello @caoguangyao,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.
