### ISSUE TITLE
same-named template in multi sub-projects

### ISSUE THREAD

**Issue by mia-san** [playframework/twirl#144]
hi there.
how can I have same-named template in multi sub-projects?

longer story:
out web app is composed of root( site root ) and some sub-apps(admin, daily, etc etc)

we have download 2.6.3, follow tutorial(esp. 'Working with sub-projects').
we managed to have 'root' project and 'admin' sub-project, works fine as long as rendering string(i.e. Ok("this is admin controller"))
so far so good.

now, we have added 'sample.scala.html' in both 'root' project and 'admin' sub-project.
but admin controller renders sample.scala.html(i.e. Ok(views.html.sample())) it seems always render 'root' template, not 'admin' one.
`sbt compile` does not complain.

I have investigated a little and found that file `/modules/admin/target/scala-2.12/twirl/main/views/html/sample.template.scala` has `package views.html` declared.
perhaps root template wins somehow.

twirl doesn't have @package directive or such, as far as I can see.
build.sbt has
`//TwirlKeys.templateImports += "com.example.controllers._"`
but there seems no way to set template's package under TwirlKeys.

we are workarounding for now by
1. creating directory under views directory(i.e. /modules/admin/app/views/admin/)
2. adding prefix to template file name(i.e. admin_index.scala.html)
but seems redundant.

Are there better ways to put template under particular package?
should I asked in playframework forum?

also #64 might be related.

thanks
//

**Comment by gmethvin** [comment]
Your other module should use a directory corresponding to the package where you want it. If you have two classes with the same name, the order is undetermined.
