### ISSUE TITLE
Alternate templating system

### ISSUE THREAD

**Issue by raderio** [playframework/twirl#156]
Add support for Java and Kotlin as template languages.
This will make possible to use twirl more often as standalone library.

**Comment by domdorn** [comment]
What do you mean by this? Allow Java/Kotlin code inside a twirl template?

**Comment by raderio** [comment]
Yes.

```
index.scala.html
index.kotlin.html
index.java.html
```

**Comment by wsargent** [comment]
You would probably have the most success by incorporating Rocker as a template language:

https://github.com/fizzed/rocker

For example, some people are using Mustache: https://gdstechnology.blog.gov.uk/2014/08/05/using-mustache-with-the-play-framework/ or with Scalate https://janhelwich.wordpress.com/tag/scalate/

**Comment by raderio** [comment]
Thanks for rocker.
