### ISSUE TITLE
Triggered execution for Twirl templates is broken

### ISSUE THREAD

**Issue by Lasering** [playframework/twirl#186]
`project/plugins.sbt`:
```scala
addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.3.15")
```

`project/build.properties`:
```properties
sbt.version = 1.2.1
```

`build.sbt`:
```scala
name := "TwirlTest"
version := "0.1"
scalaVersion := "2.12.6"
lazy val root = (project in file(".")).enablePlugins(SbtTwirl)
```

`src/main/twirl/index.scala.html`
```
@()

<html>
  <body>
  </body>
</html>
```

In sbt shell `show watchSources` (just showing relevant sources):
```
[info] * Source(
[info]   base = /home/simon/TwirlTest/src/main/twirl/index.scala.html,
[info]   includeFilter = sbt.io.AllPassFilter$@554d040d,
[info]   excludeFilter = sbt.io.NothingFilter$@3fe24670,
[info]   recursive = true,
[info] )
```

In sbt shell `~compile` then modify the `index.scala.html` in any way (eg. add more html, remove html, add parameters, remove parameters, interpolate parameters in html, etc) a compile will never be triggered.

I can test with more Sbt versions and/or Scala versions if that helps.

**Comment by marcospereira** [comment]
Hi @Lasering,

> I can test with more Sbt versions and/or Scala versions if that helps.

Better if you can create a complete project that reproduces the problem.

Thanks!

**Comment by Lasering** [comment]
https://github.com/Lasering/TwirlTriggeredExecution

I've tested on Linux with JDK10 and on Windows with JDK8. Always getting the same result.

**Comment by Lasering** [comment]
@marcospereira can you guide me to the right place where the problem might be?

**Comment by marcospereira** [comment]
Hi @Lasering, thanks for taking time to create a small reproducer.

Apparently, this is related to some changes introduced in sbt 1.1.5 (it works as expected with 1.1.4 and earlier version). A good way to check that is to compare the filters for other directory/files (for example for `src/main/scala`) with the filters for `src/main/twirl` and try to emulate them in your reproducer project.

If they work, them replicate these filters in `SbtTwirl`.

It may be work to locally test your changes with sbt 1.1.4, 1.16 and 1.2.1.

**Comment by Lasering** [comment]
I can confirm its broken starting from Sbt 1.1.5.

My findings so far (removed uninteresting entries, and slightly simplified the output):

```
SBT 1.1.4 show watchSources
* Source(
  base = /TwirlTriggeredExecution/src/main/scala,
  includeFilter = SimpleFileFilter(SimpleFilter(PatternFilter(.*\Q.java\E) | PatternFilter(.*\Q.scala\E)) && sbt.io.SimpleFileFilter),
  excludeFilter = sbt.io.HiddenFileFilter,
  recursive = true,
)
* Source(
  base = /TwirlTriggeredExecution,
  includeFilter = SimpleFileFilter(SimpleFilter(PatternFilter(.*\Q.java\E) | PatternFilter(.*\Q.scala\E)) && sbt.io.SimpleFileFilter),
  excludeFilter = sbt.io.HiddenFileFilter,
  recursive = false,
)
* Source(
  base = /TwirlTriggeredExecution/src/main/twirl/index.scala.html,
  includeFilter = sbt.io.AllPassFilter,
  excludeFilter = sbt.io.NothingFilter,
  recursive = true,
)
```

```
SBT 1.2.1 show watchSources
* Source(
  base = /TwirlTriggeredExecution/src/main/scala,
  includeFilter = SimpleFileFilter(SimpleFilter(PatternFilter(.*\Q.java\E) | PatternFilter(.*\Q.scala\E)) -- sbt.io.DirectoryFilter),
  excludeFilter = SimpleFileFilter(sbt.io.HiddenFileFilter || ManagedSourcesFilter(Set(/TwirlTriggeredExecution/target/scala-2.12/twirl/main/html/index.template.scala))),
  recursive = true,
)
* Source(
  base = /TwirlTriggeredExecution,
  includeFilter = SimpleFileFilter(SimpleFilter(PatternFilter(.*\Q.java\E) | PatternFilter(.*\Q.scala\E)) -- sbt.io.DirectoryFilter),
  excludeFilter = SimpleFileFilter(sbt.io.HiddenFileFilter || ManagedSourcesFilter(Set(/TwirlTriggeredExecution/target/scala-2.12/twirl/main/html/index.template.scala))),
  recursive = false,
)
* Source(
  base = /TwirlTriggeredExecution/src/main/twirl/index.scala.html,
  includeFilter = sbt.io.AllPassFilter,
  excludeFilter = sbt.io.NothingFilter,
  recursive = true,
)
```


It seems the `includeFilter` changed from:
```
SimpleFileFilter(SimpleFilter(PatternFilter(.*\Q.java\E) | PatternFilter(.*\Q.scala\E)) && sbt.io.SimpleFileFilter)
```
to
```
SimpleFileFilter(SimpleFilter(PatternFilter(.*\Q.java\E) | PatternFilter(.*\Q.scala\E)) -- sbt.io.DirectoryFilter),
```

Due to this https://github.com/sbt/sbt/pull/4098/files.

Also I cannot understand why `index.template.scala` is being excluded for:

- `/TwirlTriggeredExecution/src/main/scala` - the target folder is not inside `src/main/scala` so it would never be included.
- `/TwirlTriggeredExecution` - this watch is not recursive so it would never catch anything inside the target folder.

**Comment by jrudolph** [comment]
I'm seeing this as well. In any case the setup of `watchSources` in weird, because it only includes sources that are already existing in the directory:

https://github.com/playframework/twirl/blob/af0de40e811adb20301b4b197414e803bcc7f95a/sbt-twirl/src/main/scala/play/twirl/sbt/SbtTwirl.scala#L54

In spray/twirl we had this instead which watches the directory instead:

https://github.com/spray/twirl/blob/caa18e5727861ccba3116021576e7dad58893754/sbt-twirl/src/main/scala/twirl/sbt/TwirlPlugin.scala#L67-L70

Maybe the current version here only worked accidentally until sbt 1.1.4?

**Comment by jrudolph** [comment]
As a workaround you might try this instead:

```scala
watchSources +=
  WatchSource(
    (sourceDirectory in TwirlKeys.compileTemplates).value,
    "*.scala.*",
    (excludeFilter in Global).value
  )
```
