### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by bobaaaaa** [playframework/twirl#203]
Hey,
where can I find the changelog of twirl? Not the whole playframework changelog. Only a dev friendly overview (like a `CHANGELOG.md`).

**Comment by mkurz** [comment]
Did you run into issues?

**Comment by bobaaaaa** [comment]
No. I just want to check what are the new features in 1.4 :)

**Comment by mkurz** [comment]
We don't have a changelog in twirl. However not much changed for the 1.4.0 release, just some library upgrades and support for Scala 2.13.0-M5, the only new "feature" is that #50 was fixed. Have a look at the git log: https://github.com/playframework/twirl/commits/1.4.0
