### ISSUE TITLE
Deprecation warning when using varargs in Scala 2.13.0

### ISSUE THREAD

**Issue by flamingelk** [playframework/twirl#237]
When creating a template using varargs e.g.

```@(args: (Symbol, Any)*)```

the generated code causes a deprecation warning in Scala 2.13:

```Passing an explicit array value to a Scala varargs method is deprecated (since 2.13.0) and will result in a defensive copy; Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call```

I'm not sure if this will go away when [this issue](https://github.com/scala/scala/pull/7703) is released, but if a project uses `-Xfatal-warnings` this blocks compilation.

**Comment by marcospereira** [comment]
Closed by #238.
