### ISSUE TITLE
Any way to disable TwirlFeatureImports or the implicit conversions to Boolean?

### ISSUE THREAD

**Issue by andywhite37** [playframework/twirl#240]
I'm working on a play/twirl app, and we just got burned badly by the `twirlOptionToBoolean` implicit conversion in `TwirlFeatureImports.scala`, and I suspect we have many other cases where we have Options or other non-boolean values in our if statements because of presumed safety with `if`.

Is there any way to disable these implicit conversions so we can seek and destroy other non-boolean if expressions?

https://github.com/playframework/twirl/blob/master/api/shared/src/main/scala/play/twirl/api/TwirlFeatureImports.scala#L33-L38

```
/** Adds "truthiness" to iterables, making them false if they are empty. */
  implicit def twirlIterableToBoolean(x: Iterable[_]): Boolean = x != null && !x.isEmpty
  /** Adds "truthiness" to options, making them false if they are empty. */
  implicit def twirlOptionToBoolean(x: Option[_]): Boolean = x != null && x.isDefined
  /** Adds "truthiness" to strings, making them false if they are empty. */
  implicit def twirlStringToBoolean(x: String): Boolean = x != null && !x.isEmpty
```

**Comment by marcospereira** [comment]
Hey @andywhite37, you can set [`templateImports`](https://github.com/playframework/twirl/blob/21105a2113bff6135cfe908f270ba01849d648cf/sbt-twirl/src/main/scala/play/twirl/sbt/SbtTwirl.scala#L16) to `Nil` and add imports selectively, without the implicit conversions (or maybe only remove `"_root_.play.twirl.api.TwirlFeatureImports._"` from the setting).

Moreover, our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.

**Comment by andywhite37** [comment]
@marcospereira - thanks for the comment.  I understand about where to post questions in the future.

I was able to address my problem by doing what you suggested, so thanks for that.  I added the following to my build.sbt:

```scala
TwirlKeys.templateImports := (
  TwirlKeys.templateImports.value.toList
    .filter(_ != "_root_.play.twirl.api.TwirlFeatureImports._") ++
    List(
      "_root_.play.twirl.api.TwirlFeatureImports.defining",
      "_root_.play.twirl.api.TwirlFeatureImports.using"
    )
  )
```
