### ISSUE TITLE
Support modern scala.js

### ISSUE THREAD

**Issue by justjoheinz** [playframework/twirl#462]
It seems the only thing missing from support for scalajs 1.x is a release. Version 1.5.1 is still stuck on scala.js 0.6. Currently I helped myself by doing a publishLocal, but it would be nice to find current artifacts in maven.

**Comment by justjoheinz** [comment]
In case anyone is wathcing this: version 1.6.0-M1 is what is working for me...

**Comment by mkurz** [comment]
Yes I am watching, good to hear :+1:

**Comment by mkurz** [comment]
@justjoheinz Added to the 1.6.0 milestone, if you encounter problems please let us know, thanks!
