### ISSUE TITLE
Where should we publish sbt-twirl to?

### ISSUE THREAD

**Issue by mkurz** [playframework/twirl#473]
I want to publish twirl 1.6.0-M1, now I am asking myself where the sbt plugin should get published to?

The old 1.5.1 (plugin) release got published under `com.typesafe.sbt` in the read-only repo https://repo.scala-sbt.org/.
We could of course switch to `com.typesafe.sbt` on maven central, however looking at https://repo1.maven.org/maven2/com/typesafe/sbt/ it seems no one is actually publishing sbt-plugins there anymore. It seems all sbt-plugins are now moving to https://repo1.maven.org/maven2/com/github/sbt/. Actually, if you look at https://repo1.maven.org/maven2/com/typesafe/sbt/, the only newer stuff there is sbt-git, which IMHO should be published under `com.github.sbt` as well now, I don't know why they keep publishing to `com.typesafe.sbt` (started a discussion: https://github.com/sbt/sbt-git/issues/198). And sbt-play-ebean only published a RC3, and actually I think that's the same story like `sbt-twirl` here.

Shouldn't sbt-twirl (as well as sbt-play-ebean) now be published under `com.typesafe.play`?
Or I am completely wrong and should we keep it under `com.typesafe.sbt`? However, be aware that whoever wants to publish twirl then will need permissions to publish to `com.typesafe.sbt` (for the sbt-plugin) as well to `com.typesafe.play` (to publish the twirl-api,... libs).
Moving twirl (the plugin) to `com.github.sbt` would be another option, not sure however, because I think that means twirl should move to the sbt Github organization as well.

**Comment by octonato** [comment]
I vote for `com.typesafe.play`. Makes lot of sense.

**Comment by mkurz** [comment]
So everyone voted for `com.typesafe.play` :+1:
