### ISSUE TITLE
Html.apply should also accept a Option[String]

### ISSUE THREAD

**Issue by mavilein** [playframework/twirl#50]
Hey there,

i found myself recently using very often the following code throughout our template code:

```
Html(data.textOption.getOrElse(""))
```

We have lots of texts that are optional and may contain HTML tags. Therefore i find myself often writing the code above. And i thought it would be nice to have something like this out of the box with Twirl.

```
def apply(text: Option[String]): Html = {
    apply(text.getOrElse(""))
}
```

What do you think? If you like it, i can open a Pull Request.

Thx!

**Comment by mkurz** [comment]
S.ounds reasonable. See #193
