### ISSUE TITLE
scala-xml version is outdated 

### ISSUE THREAD

**Issue by griffhun** [playframework/twirl#541]
In scala 2.12 as I see the plan is to use scala-xml 1.3.0 but there is a scala-xml 2.1.0 available for scala 2.12 too.

This cause problems with sbt-native-packager plugin which is depends on scala-xml 2.1.0. And as I see for scala 3 the project already depends on scala-xml 2.1.0

**Comment by ihostage** [comment]
Hmmm 🤔 This is related with #424 and #526
@mkurz @SethTisue Do you know, why we didn't update the `scala-xml` for `2.12` too? I could't find a strict reason for that in related PR's 🤔

**Comment by griffhun** [comment]
I've figured it out the problem is probably on the sbt-native-packager side as they should not update to scala-xml 2.x if they want to be able to work as a scala plugin.
https://github.com/sbt/sbt-native-packager/issues/1517

**Comment by griffhun** [comment]
> Hmmm 🤔 This is related with #424 and #526 @mkurz @SethTisue Do you know, why we didn't update the `scala-xml` for `2.12` too? I could't find a strict reason for that in related PR's 🤔

When I tried to update:
```
[error] stack trace is suppressed; run last compiler / update for the full output
[error] (compiler / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over 1.0.6
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.6.0-M6+37-1c63ce71+20220826-1058-SNAPSHOT (depends on 2.1.0)
[error] 	    +- org.scala-lang:scala-compiler:2.12.16              (depends on 1.0.6)
```

**Comment by SethTisue** [comment]
Scala 2.12.17 will be released soon and it will include https://github.com/scala/scala/pull/10108, so you probably want to wait for 2.12.17, then upgrade Twirl, and then the versions will be in alignment.

**Comment by mkurz** [comment]
When Scala 2.12.17 comes out we want to upgrade all projects to scala-xml 2 and push new releases. I think that is the most reasonable thing to do here.

**Comment by mkurz** [comment]
Twirl  1.6.0-M7 is out with scala-xml upgraded. We might also release 1.5.2 with upgrade scala-xml to v2 as well.

**Comment by mrdziuban** [comment]
@mkurz is 1.6.0-M7 published to maven central or another repository?

**Comment by mkurz** [comment]
@mrdziuban Maven Central: https://repo1.maven.org/maven2/com/typesafe/play/twirl-api_2.13/

**Comment by mrdziuban** [comment]
Aha, I had missed that `sbt-twirl` migrated to the `com.typesafe.play` namespace -- thank you!
