### ISSUE TITLE
sbt-twirl generates code that is no longer supported and/or deprecated in Scala 3

### ISSUE THREAD

**Issue by tmiseikis** [playframework/twirl#591]
**Scala version:** 3.2.1
**sbt-twirl version:** 1.6.0-M7

The following issues are reported by Scala 3 compiler in the files generated by sbt-twirl:
- `_` is no longer supported for a wildcard import; use `*` instead 
This construct can be rewritten automatically under -rewrite -source future-migration.

```
import _root_.play.twirl.api.TwirlFeatureImports._
import _root_.play.twirl.api.TwirlHelperImports._
```

- Unless class BaseScalaTemplate is declared 'open', its extension in a separate file should be enabled by adding the import clause 'import scala.language.adhocExtensions' or by setting the compiler option -language:adhocExtensions.
See the Scala docs for value scala.language.adhocExtensions for a discussion why the feature should be explicitly enabled.

**Comment by mkurz** [comment]
@tmiseikis Would you have time to provide a PR for this? @xuwei-k @tototoshi Maybe you?

**Comment by tototoshi** [comment]
To solve this problem, sbt-plugin and TwirlCompiler need to be able to select the version of Scala code that is generated from the template.

What I need to do is
- to add a configuration key for sbt-plugin like `generatedCodeScalaVersion`
- to make `TwirlCompiler.compile` generate the appropriate code for each version of Scala

**Comment by ahjohannessen** [comment]
Could this not be solved by:

```
templateImports  := TwirlCompiler.defaultImports(scalaVersion.value),
```

**Comment by tototoshi** [comment]
@ahjohannessen Thank you. I did exactly what you said.
