### ISSUE TITLE
@import should be valid before the template signature

### ISSUE THREAD

**Issue by Lasering** [playframework/twirl#60]
If @import was valid before the template signature one could have this:

```
@import org.some.example.package.Customer

@(customer: Customer, orders: List[Order])

<h1>Welcome @customer.name!</h1>
<ul>
@for(order <- orders) {
  <li>@order.title</li>
}
</ul>
```

Instead of this:

```
@(customer: org.some.example.package.Customer, orders: List[Order])

@import org.some.example.package.Customer

<h1>Welcome @customer.name!</h1>
<ul>
@for(order <- orders) {
  <li>@order.title</li>
}
</ul>
```

**Comment by kflorence** [comment]
@pvlugter is there an easy way to tell which version of Play this got into?

**Comment by kflorence** [comment]
Looks like it's not in Play master yet: https://github.com/playframework/playframework/blob/master/framework/project/plugins.sbt

**Comment by kflorence** [comment]
Created https://github.com/playframework/playframework/pull/3821

**Comment by pvlugter** [comment]
The commit that added top imports is in twirl 1.0.+. Available in Play 2.3 and 2.4 milestones.

https://github.com/pvlugter/twirl/commit/fd35a3338141734f14e77ada3ced19e7f9062f2f

```
git tag --contains fd35a3338141734f14e77ada3ced19e7f9062f2f
v1.0.0
v1.0.0-RC1
v1.0.0-RC2
v1.0.0-RC3
v1.0.1
v1.0.2
v1.0.3
v1.0.4
```

**Comment by kflorence** [comment]
Hmm, @pvlugter in that case the problem I'm seeing might be related to the Scala IDEA plugin (having @import at the top seems to compile fine, but it breaks syntax highlighting in IDEA).

**Comment by kflorence** [comment]
@pvlugter this seems to be the case, and looks like there is already a ticket for it: https://youtrack.jetbrains.com/issue/SCL-8030 (sorry for time wasted, sometimes it's hard to tell where these problems lie).
