### ISSUE TITLE
Release version 1.6.0

### ISSUE THREAD

**Issue by dalbani** [playframework/twirl#628]
Hello,

For the lack of a better way to ask the question, I misuse this issue section to ask for an update on the release of version 1.6.0.
I couldn't find an explicit list of blocking issues or missing features.
Is there a way to help finishing up the RC round?

The reason I'm asking is because [Twirl 1.6.0 is appparently the missing bit for a release of Scalatra 3.0.0](https://github.com/scalatra/scalatra/issues/1528#issuecomment-1581090228).

Thanks!

**Comment by mkurz** [comment]
I am very sorry for the delay, urgent family related things kept me pretty much away from keyboard the last two weeks, I hope next week finally I can catch up here also with a twirl release.

**Comment by dalbani** [comment]
Thanks for your quick reaction.
No problem, family is obviously more important than anything else.

**Comment by BardurArantsson** [comment]
Ping!

**Comment by dalbani** [comment]
Hi @mkurz, I hope things are going fine at home on your side.
Do you think you could make a release in the near future? Thanks!

**Comment by mkurz** [comment]
Release will happen this week, 100%

**Comment by mkurz** [comment]
Twirl 1.6.0 released:
https://github.com/playframework/twirl/releases/tag/1.6.0
