### ISSUE TITLE
Is 1.0.2 available in some repository?

### ISSUE THREAD

**Issue by your-diary** [playframework/twirl#690]
I'm trying to build a legacy Scala project which depends on `sbt-twirl 1.0.2`.
However, for example, [maven central](https://central.sonatype.com/artifact/com.typesafe.play/sbt-twirl/versions) doesn't provide the version; only `1.5.2` or newer are available.

Is `1.0.2` available via some repository?

**Comment by mkurz** [comment]
It can be found here: https://scala.jfrog.io/ui/native/sbt-plugin-releases/com.typesafe.sbt/sbt-twirl/

**Comment by your-diary** [comment]
@mkurz Thank you! This is exactly what I wanted.

**Comment by mkurz** [comment]
Be aware to use https://repo.scala-sbt.org/, not https://scala.jfrog.io/ which I posted initially. It's a redirect. (I edited my comment)

**Comment by your-diary** [comment]
@mkurz

I see. Thanks.

> *This is a redirection service for the sbt community repository. To insulate yourself from future migrations, please use the proxy URL instead of where it redirects*
