### ISSUE TITLE
Allow option to not import TemplateMagic._ in templates by default

### ISSUE THREAD

**Issue by kflorence** [playframework/twirl#71]
I see here that the import is hard-coded: https://github.com/playframework/twirl/blob/e36a84922f933bb441b736560c7a6fb22f2b934a/compiler/src/main/scala/play/twirl/compiler/TwirlCompiler.scala#L332

In our case, this import is not desired and ends up conflicting with our own internal `RichDate` class. It would be nice to be able to configure Twirl to not include that import by default.

**Comment by kflorence** [comment]
Alternatively, perhaps the String/Date helpers could be moved elsewhere since it looks like there are some syntax related functions in that file as well.

**Comment by jroper** [comment]
Some of the things provided by `TemplateMagic` are needed.  Others are not.  We should probably do something like this:

* Rename `TemplateMagic` to `TemplateFunctions`.  It's not magic, most of it is a core part of template features.
* Deprecate `Default.?:`.  I've never heard of it before.  It's not documented, I don't know if it's used anywhere by anyone.
* Move `javaCollectionToScala`, `richDate` and `richString` to the appropriate utility classes in `Play`.

**Comment by kflorence** [comment]
@jroper that sounds very reasonable. I also don't think those utility classes are documented anywhere, I didn't even know they existed until upgrading to Play 2.3.8 and getting errors when they collided with our own.
