### ISSUE TITLE
Support for more than 22 arguments in the twirl template

### ISSUE THREAD

**Issue by JamesWilson3** [playframework/twirl#722]
Hi @mkurz,

I read that Scala 3 has now removed the restrictions regarding the 22 parameter limits (https://docs.scala-lang.org/scala3/reference/dropped-features/limit22.html)

I have also upgraded to using Play 3 with the Scala 3, but I am still encountering the error (when trying to have 23 arguments in the template):

`play.sbt.PlayExceptions$CompilationException: Compilation error[type Template23 is not a member of play.twirl.api`

Just wondering whether the removal of the 22 parameters limit in Scala 3 has any bearing on the 22 parameter limitations in the template, and if there are any additional changes that needs to be done to make the template support for greater than 22 parameters.

**Comment by mkurz** [comment]
Might be possible that twirl tries to detect how many args are given and based on this is generates the scala files, not sure, just looking at https://github.com/playframework/twirl/blob/main/api/shared/src/main/scala/play/twirl/api/Template.scala
So it looks like twirl needs to be fixed to support Scala 3 removal of the 22 parameter limit?
Would you want to work on this and provide a PR?

**Comment by mkurz** [comment]
If you use Play Java, then just stay on Scala 2.13 for now. If you don't have any Scala code in your project it will make absolutely no difference for you which Scala version you use.
And then just watch this issue until it gets resolved 😉

**Comment by mkurz** [comment]
So I couldn't resist and came up with 
- #747

as experiment to see if that works.

**Comment by mkurz** [comment]
- Fixed in #747
- Will be part of Twirl's next patch releases 2.0.5 and 1.6.6 and Play's 3.0.3/2.9.3
