### ISSUE TITLE
Extended Template: too many arguments for method error 

### ISSUE THREAD

**Issue by slimandslam** [playframework/twirl#81]
To recreate, download the minimal 2.4.0 Play framework from here:

http://downloads.typesafe.com/typesafe-activator/1.3.4/typesafe-activator-1.3.4-minimal.zip

Create a new Java play app:

$ activator new testapp play-java

Following the directions at the bottom of this document:

https://github.com/playframework/twirl/blob/master/docs/manual/working/javaGuide/main/templates/JavaTemplateUseCases.md

I have an extended template that needs an extra script.

Edit the file index.scala.html so it looks like this:

     @(message: String)

     @scripts = {
         <script type="text/javascript">alert("hello !");</script>
     }

     @main("Welcome to Play",scripts) {

         @play20.welcome(message, style = "Java")

     }

Then compile with activator. This is the output:

[info] Compiling 6 Scala sources and 2 Java sources to /testapp/target/scala-2.11/classes...
[error] /testapp/app/views/index.scala.html:7: too many arguments for method apply: (title: String)(content: play.twirl.api.Html)play.twirl.api.HtmlFormat.Appendable in class main
[error] @main("Welcome to Play",scripts) {
[error]      ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed

**Comment by wsargent** [comment]
FYI, you can reference the generated HTML here: https://www.playframework.com/documentation/2.4.x/JavaTemplateUseCases

**Comment by slimandslam** [comment]
Thanks. I don't know how I missed that. Not enough sleep, I guess.

J

**Comment by jroper** [comment]
Did you update your `main.scala.html` template?

**Comment by slimandslam** [comment]
Yes. It works fine. Thanks.

J

**Comment by marcospereira** [comment]
Should we close this issue?

**Comment by slimandslam** [comment]
Yes.

J
