### ISSUE TITLE
scalajs support

### ISSUE THREAD

**Issue by antonkulaga** [playframework/twirl#82]
It will be great to be able to share some templates between backend and frontend

**Comment by Jentsch** [comment]
I looked into in to this problem. With very few changes I got a minimal example application running:

- adding the ScalaJS plugin and enabling it in the api project
- removing Apache common-lang3 as dependency and replacing the two usages by dummies. Referenced code could be duplicated (Licence?) or replaced by a Scala library with ScalaJS support (which?).
- a other issue is the scala xml module, which also doesn't support ScalaJS. I tried to port that two, but without quick success, so I deleted the two occurrences in BaseScalaTemplate.scala
- removing stuff that use reflection, again in the BaseScalaTemplate.scala file: replace Manifest by ClassTag and dropped line with invocation of `getClass`
- adding `"com.typesafe.play" %%% "twirl-api" % "1.2.1-SNAPSHOT"` as dependency in the depending project.

With that I got:
- A minimal working play-scalaJs application that uses twirl for front end snippets :-)
- horrible test failures in `sbt test`

**Comment by raderio** [comment]
https://github.com/playframework/twirl/pull/109

**Comment by raderio** [comment]
it's done https://github.com/playframework/twirl/commit/104128a41ed3cecfd329f1721d5f7ae4cf0286d7

**Comment by mkurz** [comment]
Fixed via #109
