### ISSUE TITLE
Gradle Support

### ISSUE THREAD

**Issue by schmitch** [playframework/twirl#83]
Currently Twirl only works on sbt, is there any work to also have a working gradle/maven plugin?

**Comment by JakeWharton** [comment]
I wrote a Maven one recently for a thing I needed:
https://github.com/JakeWharton/twirl-maven-plugin

**Comment by jroper** [comment]
There's no reason why a gradle plugin couldn't be written for it, the compiler itself is a separate artifact from the sbt plugin. But as I, and as far as I'm aware everyone else that maintains Twirl has no gradle experience, it's not something that we're going to provide.

**Comment by JakeWharton** [comment]
A Gradle plugin would be _especially_ nice given the forthcoming [continuous build mode][1] in v2.5 (ala sbt).

 [1]: https://docs.gradle.org/release-candidate/release-notes#continuous-build

**Comment by schmitch** [comment]
@jroper it would be nice, since Gradle will provide Playframework support, however it already provides template compilation of Twirl, however it would be great if there is a play-twirl plugin and not just a big monolithic play plugin. And I thought that maybe twirl itself could provide that as an alternative to sbt.

**Comment by jroper** [comment]
If someone submits a PR adding a gradle module, I'd be willing to consider it.  The most important thing though is that it has adequate test coverage - given my complete lack of gradle knowledge, in order to maintain quality, we're going to have to have comprehensive tests of the gradle support so that I can be confident that changes to break it.

**Comment by raderio** [comment]
https://github.com/67726e/gradle-twirl

**Comment by benmccann** [comment]
Gradle now has built-in support for Play and thus Twirl. Though I'm not sure you can use the Twirl compiler independently of Play when using Gradle

**Comment by benmccann** [comment]
If anyone would like to help improve Maven/Gradle support I filed a related issue: https://github.com/playframework/twirl/issues/177

**Comment by ihostage** [comment]
Maven part is moved to separate issue #581

**Comment by ihostage** [comment]
8 years waiting and we've done it 🕺 
Congratulations, folks! 🎉
