### ISSUE TITLE
Template naming not consistent

### ISSUE THREAD

**Issue by rtatavarty** [playframework/twirl#91]
I have a project with a simple template `login.scala.html` and it generated `views.html.**login**.template.scala` in an activator compilation but in pure sbt build it generated  `views.html.**logIn**.template.scala`. Naturally, this is resulting in compilation errors and broken builds.

Is there any way to force naming style (as-is/camelCase)? Or is there any best practice to be consistent across builds?

Thanks!

**Comment by wsargent** [comment]
The only thing I can think of is that at one point the file was called logIn.scala.html and then the case was changed.  If you do a clean, then that will remove target files, but there are filesystems which are case-insensitive and so may not pick up that there was a change there.

**Comment by wsargent** [comment]
@rtatavarty can you reproduce this issue with a test case?
