### ISSUE TITLE
Injectable templates

### ISSUE THREAD

**Issue by jroper** [playframework/twirl#93]
One problem with eliminating global state in Play is that now everything, eg CSRF, i18n, reverse routing, assets rendering etc needs to be passed into each template every time its invoked.  This is manageable (though not ideal) in Scala, but for Java users it leaves a lot to be desired.  One solution to this is to make templates themselves injectable.  I propose the following syntax:

```scala
@*
 * Some template
 *@
@this(templateContext: Context)

@(title: String)

...
```

The `this` keyword will be for defining constructors.  `this` is already a reserved word in Twirl by virtue of the fact that it's a Scala reserved word, and the `this()` syntax is somewhat consistent with Scala constructor syntax.  The above template would compile (roughly) to this:

```scala
class someTemplate @Inject() (templateContext: Context) extends Template1[String] {
  def apply(title: String) = { ... }
}
```

while, if no `@this` directive is specified, it will be compiled to an `object` as before.  Hence this should be 100% backwards compatible.

Templates could of course depend on each other, by declaring each other in their constructors, for example, the `index` template might depend on the `main` template:

**main.scala.html**:

```scala
@this(templateContext: Context)

@(title: String)(content: Html)

<html>
  <head><title>@title</title></head>
  <body>@content</body>
</html>
```

**index.scala.html**:

```scala
@this(templateContext: Context, main: views.html.main)

@main("Index") {
  <h1>Hello world!</h1>
}
```

Note that of course the `Context` type above is just a fictitious type that we may provide in Play as a convenience to provide web template utilities in one place, such as i18n, assets reverse routing/CDN/finger printing configuration, CSRF config, etc.

**Comment by mariussoutier** [comment]
Nice proposal. I think introducing `Context` would solve most problems already (as an implicit in Scala at least).

**Comment by lavrov** [comment]
Is it possible to implement CI for `routes` file? That would allow us to inject `QueryStringBindable` and `PathBindable` instances.

**Comment by makkarpov** [comment]
How this proposal would deal with situation where template references **a lot** of dependent templates, like form builders:

```scala
// textField.scala.html
@this(lang: MessagesAPI)
@(...)(implicit rq: RequestHeader)
....
```

And main template:

```scala
// form.scala.html
@this(lang: MessagesAPI, textField: views.textField, passwordField: views.passwordField, selectField: views.selectField, checkboxField: views.checkboxField, radioField: views.radioField, /* ... */)
```

Currently it at least ugly.

**Comment by jroper** [comment]
I don't think the form builders will be made injectable, they'll be kept as objects. Note that there's no reason why injected templates can't invoke non injected templates, and vice versa (if the injected template is passed as a parameter).

So the form builders will be kept as not injected, and have implicit dependencies on the messages API, and any templates that use them will just need to have the messages API template injected.

**Comment by eximius313** [comment]
Would this also works if I need to inject Service or Dao?

Let's say that I have ```navbar``` template, that displays user's picture (when user is logged in) and I dont want to pass ```User``` object in each of my 100 templates for just being used in ```navbar```.
Can I just inject ```userService``` and retrieve picture in ```navbar``` template?

Kind regards
