### ISSUE TITLE
The default, one-arg behaviors for Html default to unsafe behavior.

### ISSUE THREAD

**Issue by farmdawgnation** [playframework/twirl#94]
I was paging through the API this morning and discovered that the `Html` class contains facilities for escaping text passed into it, but the behavior is opt-in instead of opt out. The one-arg constructors explicitly disable the behavior:

```scala
class Html private[api] (elements: immutable.Seq[Html], text: String, escape: Boolean) extends BufferedContent[Html](elements, text) {
  def this(text: String) = this(Nil, Formats.safe(text), false)
  def this(elements: immutable.Seq[Html]) = this(elements, "", false)
```

This seems like bad practice for library consumers. Is there reasoning why this was done or could this be defaulted to true in a future release?

**Comment by wsargent** [comment]
Calling `HTML()` itself is the escape behavior -- you have to wrap text in it explicitly in a Twirl template.  Html() is needed for rendering page fragments, but it's not something you should call from Java code or on unvalidated/untrusted user input.

There is a youtube video talking about good and bad practice: https://youtu.be/gCRWvlmX7Is?t=18m9s

**Comment by farmdawgnation** [comment]
Wouldn't be the first time we were using something wrong. Cheers.
